
data:
  #   "gs://fantom_dataset/fantom_v1.json"
  #   "https://storage.googleapis.com/fantom_dataset/fantom_v1.json"
  #   "data/fantom_v1.json"
  fantom_url: "gs://fantom_dataset/fantom_v1.json"

  context_field: "full_context"   # or "short_context"

eval:
  model_name: "gemini-2.5-flash" 
  max_examples: null             # or null to use all examples
  output_path: "fantom_factq_gemini_flash.csv"
  task_type: "FactQ" # or "beliefQ / info-access"
